### ISSUE TITLE
[Issue Report] Nethru - Issue of including our company's data analysis scripts on your filter list

### ISSUE THREAD

**Issue by sung-uk** [SlowMemory/List-KR#113] opened 2017-04-26 04:55 UTC
Dear SlowMemory,

Thank you for updating the list for the clear web-surfing experience. This is Nethru (nethru.co.kr) which is located in Seoul, South Korea and we have been providing data analysis software and service for many customers for 17 years. (Link: http://nethru.co.kr/en/main.php)

We recently found that there were several scripts that we have used for the data collection plus data analysis for our customers on your list. We want to ask you to remove our company’s scripts and text on your list for our successful customer service.

Here is the list that we want to ask you to delete on the list:
/weblog/nethruscriptlog.html^
/wloso.html?wlo_so=
/wlo/Logging^
/wlo/UserLogging^
||yes24.com//javascript/wlo.js
||shinhan.com^*n_click_logging.shb?

In addition to these, we want to ask you not to put below four scripts on your filter list in the future for our customer service. We have used these for our service very commonly, so please do not put these on your filter list in the future.
**wlo.js
makePcookie.js
siteoverlay.js
wl6.js**

If you want to contact to us via e-mail, here is our email: das(at)nethru.co.kr 

We will be looking forward to receiving positive answer and thank you for your help.

Sincerely,

Nethru

**Comment by SlowMemory** [comment] 2017-04-27 04:24
Dear sung-uk,

Hello, thank you for reaching out. 

Regarding the issue you’ve reported, it is not a bug nor an issue of the filter list.

I have articulated in [README.md](https://github.com/SlowMemory/List-KR/blob/master/README.md) and in the [main homepage](https://list-kr.github.io/) that this filter aims to block trackers.

As such, when a request found to be sending potentially identifying information of users, including user agent strings, screen resolutions, or when a certain resource found to be collecting and transferring user’s information to third-party or setting personally identifying cookies, such requests will be blocked in this filter.

The criteria is similar to [“EasyPrivacy policy” ](https://easylist.to/pages/policy.html), which is the policy of the most widely used block list for blocking trackers. Please refer to the link for more detailed descriptions.

The lines you’ve quoted from the filter are included in the block list because it found to be meet above criteria, as well as other entries below `! ------ Spyware ----------------`. There is no other reason. Only occasions when a filter rule gets deleted are when it turns out to be obsolete and not meeting the criteria; or when it causes undesirable side effects. For instance, when a rule blocks a website’s necessary resource and thereby breaking its main functionality, it will be removed.

This filter is for people who want to block all Korean advertisements and trackers. It would be unfair if certain requests are whitelisted upon request, also it will be a betrayal to users of this filter. If you explain that certain requests currently blocked by this filter are not used to track users, I will remove the corresponding rule. I hope this clarifies the situation.


Best,

SlowMemory

**Closed** 2017-04-28 01:22 UTC
